name: pokedex
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/loading_pokemon.gif
    - assets/
    - assets/icons/
    - assets/Pokemon Hollow.ttf
    - assets/Pokemon Solid.ttf

  fonts:
    - family: Pokemon
      fonts:
        - asset: assets/Pokemon Solid.ttf
    - family: Pokemon2
      fonts:
        - asset: assets/Pokemon Hollow.ttf

